// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.0
// source: buyback.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeId   uint32 `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Quantity uint32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *ReqItem) Reset() {
	*x = ReqItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buyback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqItem) ProtoMessage() {}

func (x *ReqItem) ProtoReflect() protoreflect.Message {
	mi := &file_buyback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqItem.ProtoReflect.Descriptor instead.
func (*ReqItem) Descriptor() ([]byte, []int) {
	return file_buyback_proto_rawDescGZIP(), []int{0}
}

func (x *ReqItem) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *ReqItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BuyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items    []*ReqItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Language string     `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Location string     `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *BuyReq) Reset() {
	*x = BuyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buyback_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyReq) ProtoMessage() {}

func (x *BuyReq) ProtoReflect() protoreflect.Message {
	mi := &file_buyback_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyReq.ProtoReflect.Descriptor instead.
func (*BuyReq) Descriptor() ([]byte, []int) {
	return file_buyback_proto_rawDescGZIP(), []int{1}
}

func (x *BuyReq) GetItems() []*ReqItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BuyReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BuyReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash     string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *CheckReq) Reset() {
	*x = CheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buyback_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReq) ProtoMessage() {}

func (x *CheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_buyback_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReq.ProtoReflect.Descriptor instead.
func (*CheckReq) Descriptor() ([]byte, []int) {
	return file_buyback_proto_rawDescGZIP(), []int{2}
}

func (x *CheckReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CheckReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type RepItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeId       uint32           `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	ParentTypeId uint32           `protobuf:"varint,2,opt,name=parent_type_id,json=parentTypeId,proto3" json:"parent_type_id,omitempty"`
	Quantity     float64          `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Name         string           `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PricePer     float64          `protobuf:"fixed64,5,opt,name=price_per,json=pricePer,proto3" json:"price_per,omitempty"`
	Description  string           `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Accepted     bool             `protobuf:"varint,7,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Meta         *structpb.Struct `protobuf:"bytes,8,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *RepItem) Reset() {
	*x = RepItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buyback_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepItem) ProtoMessage() {}

func (x *RepItem) ProtoReflect() protoreflect.Message {
	mi := &file_buyback_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepItem.ProtoReflect.Descriptor instead.
func (*RepItem) Descriptor() ([]byte, []int) {
	return file_buyback_proto_rawDescGZIP(), []int{3}
}

func (x *RepItem) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *RepItem) GetParentTypeId() uint32 {
	if x != nil {
		return x.ParentTypeId
	}
	return 0
}

func (x *RepItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RepItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepItem) GetPricePer() float64 {
	if x != nil {
		return x.PricePer
	}
	return 0
}

func (x *RepItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RepItem) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RepItem) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Rep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items     []*RepItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Hash      string     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Sum       float64    `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	Timestamp uint64     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version   string     `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Location  string     `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *Rep) Reset() {
	*x = Rep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buyback_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rep) ProtoMessage() {}

func (x *Rep) ProtoReflect() protoreflect.Message {
	mi := &file_buyback_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rep.ProtoReflect.Descriptor instead.
func (*Rep) Descriptor() ([]byte, []int) {
	return file_buyback_proto_rawDescGZIP(), []int{4}
}

func (x *Rep) GetItems() []*RepItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Rep) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Rep) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Rep) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Rep) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Rep) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_buyback_proto protoreflect.FileDescriptor

var file_buyback_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x75, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x62, 0x75, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x6e, 0x0a, 0x06,
	0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x75, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x08,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x80, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x70,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x2b,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0xad, 0x01, 0x0a, 0x03,
	0x52, 0x65, 0x70, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x75, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x71, 0x0a, 0x07, 0x42,
	0x75, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x34, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x17, 0x2e, 0x62, 0x75, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x62, 0x75, 0x79, 0x62, 0x61,
	0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x12, 0x30, 0x0a, 0x03,
	0x42, 0x75, 0x79, 0x12, 0x15, 0x2e, 0x62, 0x75, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x62, 0x75, 0x79,
	0x62, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x42, 0x08,
	0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buyback_proto_rawDescOnce sync.Once
	file_buyback_proto_rawDescData = file_buyback_proto_rawDesc
)

func file_buyback_proto_rawDescGZIP() []byte {
	file_buyback_proto_rawDescOnce.Do(func() {
		file_buyback_proto_rawDescData = protoimpl.X.CompressGZIP(file_buyback_proto_rawDescData)
	})
	return file_buyback_proto_rawDescData
}

var file_buyback_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_buyback_proto_goTypes = []interface{}{
	(*ReqItem)(nil),         // 0: buyback_proto.ReqItem
	(*BuyReq)(nil),          // 1: buyback_proto.BuyReq
	(*CheckReq)(nil),        // 2: buyback_proto.CheckReq
	(*RepItem)(nil),         // 3: buyback_proto.RepItem
	(*Rep)(nil),             // 4: buyback_proto.Rep
	(*structpb.Struct)(nil), // 5: google.protobuf.Struct
}
var file_buyback_proto_depIdxs = []int32{
	0, // 0: buyback_proto.BuyReq.items:type_name -> buyback_proto.ReqItem
	5, // 1: buyback_proto.RepItem.meta:type_name -> google.protobuf.Struct
	3, // 2: buyback_proto.Rep.items:type_name -> buyback_proto.RepItem
	2, // 3: buyback_proto.Buyback.Check:input_type -> buyback_proto.CheckReq
	1, // 4: buyback_proto.Buyback.Buy:input_type -> buyback_proto.BuyReq
	4, // 5: buyback_proto.Buyback.Check:output_type -> buyback_proto.Rep
	4, // 6: buyback_proto.Buyback.Buy:output_type -> buyback_proto.Rep
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_buyback_proto_init() }
func file_buyback_proto_init() {
	if File_buyback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buyback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buyback_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buyback_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buyback_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buyback_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buyback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buyback_proto_goTypes,
		DependencyIndexes: file_buyback_proto_depIdxs,
		MessageInfos:      file_buyback_proto_msgTypes,
	}.Build()
	File_buyback_proto = out.File
	file_buyback_proto_rawDesc = nil
	file_buyback_proto_goTypes = nil
	file_buyback_proto_depIdxs = nil
}
